version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Pastikan path Dockerfile sudah benar
    image: my-app  # Nama image yang akan dibangun secara lokal
    env_file:
      - .env
    ports:
      - "3000:3000"
