version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PLATFORM=linux/amd64,linux/arm64
    image: hanifnr11/my-app
    env_file:
      - .env
    ports:
      - "3000:3000"
