name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          echo "EC2_HOST is: ${{ secrets.EC2_HOST }}"
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -v ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
          
      - name: Deploy to EC2
        run: |
          ssh -tt ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/my-app
            git fetch origin
            git reset --hard origin/master  # Force sync dengan remote
            docker-compose down
            docker-compose pull
            docker-compose up -d
          EOF
